services:
  - type: web
    name: orchard-capitals-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_ORIGIN
        sync: false
      - key: NEXT_PUBLIC_APP_BACKEND_ORIGIN
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
        sync: false
