services:
  - type: web
    name: orchard-capitals-frontend
    runtime: node
    buildCommand: >
      npm install &&
      npm run build &&
      cp -r .next/static .next/standalone/.next/static &&
      cp -r public .next/standalone/public
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: 0.0.0.0
      - key: BACKEND_ORIGIN
        sync: false
      - key: NEXT_PUBLIC_APP_BACKEND_ORIGIN
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
        sync: false
